### ISSUE TITLE
Error 500 on install

### ISSUE THREAD

**Issue by tbba** [MoritzLost/ProcessCacheControl#1]
**ParseError syntax error, unexpected ')'**
file: .../ProcessCacheControl.module:129

`
127:                    self::MODULE_PERMISSION,
128:                    $actionPermissionName,
129:                ));
130:            } else {
`
After removing the comma after $actionPermissionName, the Installation finished ok.

Thanks for the module. Great idea!

PHP 7.3 PW - latest dev

**Comment by MoritzLost** [comment]
Thanks for the report @tbba, I just pushed a new version that removes the trailing comma. It's allowed in PHP 7.4, I guess I forgot to test the last version I published in PHP 7.3 and below. Let me know if you have any more trouble after the update!

**Comment by tbba** [comment]
Thanks for the fix :-) 
I close the issue now because, after my manual removing of the comma the install worked fine already.
