### ISSUE TITLE
typos / grammar

### ISSUE THREAD

**Issue by jlahijani** [MoritzLost/ProcessCacheControl#2]
Those options control what happens when you the default "Clear all" action is executed.

Change to...

These options control what happens when the default "Clear All" action is executed.

**Comment by MoritzLost** [comment]
Thanks for the report @jlahijani, I have corrected that sentence on the master branch. Except for the title-case spelling of "Clear All". This was indeed inconsistent with the field label, so I have changed it to "Change all" everywhere instead.

Let me know if you find any other errors!
